ARG FROM_IMAGE
FROM ${FROM_IMAGE}

RUN pip --no-cache-dir install --upgrade jupyter jupyterlab ipykernel ipython jedi

EXPOSE 8888

RUN mkdir /workspace
WORKDIR /workspace

CMD ["jupyter-lab", "--port=8888", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
